In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.svm import SVR
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

## 1. Load dataset

In [3]:
df = pd.read_csv('data/student.csv')
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
X = df.drop(columns=['math_score'])
y = df['math_score']

## 2. Train test split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [6]:
X_train.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'reading_score', 'writing_score'],
      dtype='str')

## 3. Feature groups

In [7]:
numeric_features = X_train.select_dtypes(exclude=['object', 'string']).columns.tolist()
categorical_features = X_train.select_dtypes(include=['object', 'string']).columns.tolist()
print(f"Numeric features: {numeric_features}")
print(f"categorical features: {categorical_features}")

Numeric features: ['reading_score', 'writing_score']
categorical features: ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

In [8]:
X_train['parental_level_of_education'].unique()

<StringArray>
[  'some high school',       'some college',        'high school',
  'bachelor's degree', 'associate's degree',    'master's degree']
Length: 6, dtype: str

In [9]:
ordinal_features = ['parental_level_of_education']
education_order = ['some high school', 'high school', 'some college', "associate's degree", "bachelor's degree", "master's degree"]
nominal_features = [col for col in categorical_features if col not in ordinal_features]

In [10]:
print(f"Nominal features: {nominal_features}")

Nominal features: ['gender', 'race_ethnicity', 'lunch', 'test_preparation_course']

## 4. Pipelines per feature type

In [11]:
numeric_pipeline = Pipeline([('imputer', SimpleImputer(strategy='mean')), ('scaler', StandardScaler())])
nominal_pipeline = Pipeline([('imputer', SimpleImputer(strategy='most_frequent')), ('encoder', OneHotEncoder(handle_unknown="ignore", drop='first', sparse_output=True))])
ordinal_pipeline = Pipeline([('imputer', SimpleImputer(strategy='most_frequent')), ('encoder', OrdinalEncoder(categories=[education_order], handle_unknown="use_encoded_value", unknown_value=-1))])

In [12]:
preprocessor = ColumnTransformer([('numeric', numeric_pipeline, numeric_features), ('nominal', nominal_pipeline, nominal_features), ('ordinal', ordinal_pipeline, ordinal_features)])

## 5. Full pipeline with model

In [13]:
model = LinearRegression()

model_pipeline = Pipeline([('preprocessor', preprocessor), ('model', model)])

## 6. Fit the model

In [14]:
model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['reading_score',
                                                   'writing_score']),
                                                 ('nominal',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['gender', 'race_ethni...
                                                 ('ordinal',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['some '
                                                                                               'high '
                                                                                               'school',
                                                                                               'high '
                                                                                               'school',
                                                                                               'some '
                                                                                               'college',
                                                                                               "associate's "
                                                                                               'degree',
                                                                                               "bachelor's "
                                                                                               'degree',
                                                                                               "master's "
                                                                                               'degree']],
                                                                                  handle_unknown='use_encoded_value',
                                                                                  unknown_value=-1))]),
                                                  ['parental_level_of_education'])])),
                ('model', LinearRegression())])

## 7. Model evaluation on test set

In [15]:
def evaluate_model(X, y):
    y_pred = model_pipeline.predict(X)
    mse = mean_squared_error(y, y_pred)
    mae = mean_absolute_error(y, y_pred)
    r2 = r2_score(y, y_pred)
    return mse, mae, r2

## 8. Testing various models

In [16]:
models = {'Linear Regression': LinearRegression(),
'Lasso': Lasso(),
'Ridge': Ridge(),
'Decision Tree': DecisionTreeRegressor(),
'Random Forest': RandomForestRegressor(),
'Ada Boost': AdaBoostRegressor(),
'K Neighbors': KNeighborsRegressor(),
'SVR': SVR(),
'Catboost': CatBoostRegressor(),
'Xgboost': XGBRegressor()}

In [17]:
eval_metrics = pd.DataFrame(np.nan, index=models.keys(), columns=['train_mse', 'train_mae', 'train_r2', 'test_mse', 'test_mae', 'test_r2'])

In [18]:
for k, v in models.items():
    model_pipeline = Pipeline([('preprocessing', preprocessor), ('model', v)])
    model_pipeline.fit(X_train, y_train)
    print(f"Training Model: {k}\n")
    mse, mae, r2 = evaluate_model(X_train, y_train)
    eval_metrics.loc[k, 'train_mse'] = mse
    eval_metrics.loc[k, 'train_mae'] = mae
    eval_metrics.loc[k, 'train_r2'] = r2

    mse, mae, r2 = evaluate_model(X_test, y_test)
    eval_metrics.loc[k, 'test_mse'] = mse
    eval_metrics.loc[k, 'test_mae'] = mae
    eval_metrics.loc[k, 'test_r2'] = r2

Training Model: Linear Regression

Training Model: Lasso

Training Model: Ridge

Training Model: Decision Tree

Training Model: Random Forest

Training Model: Ada Boost

Training Model: K Neighbors

Training Model: SVR

Learning rate set to 0.039525
0:	learn: 14.9429672	total: 128ms	remaining: 2m 8s
1:	learn: 14.5385154	total: 129ms	remaining: 1m 4s
2:	learn: 14.1766416	total: 130ms	remaining: 43.1s
3:	learn: 13.8996662	total: 130ms	remaining: 32.4s
4:	learn: 13.5223696	total: 131ms	remaining: 26s
5:	learn: 13.1907559	total: 131ms	remaining: 21.7s
6:	learn: 12.9654438	total: 131ms	remaining: 18.6s
7:	learn: 12.6702403	total: 132ms	remaining: 16.4s
8:	learn: 12.3548606	total: 132ms	remaining: 14.6s
9:	learn: 12.0419582	total: 133ms	remaining: 13.2s
10:	learn: 11.7665549	total: 133ms	remaining: 12s
11:	learn: 11.4924477	total: 134ms	remaining: 11s
12:	learn: 11.2335176	total: 135ms	remaining: 10.2s
13:	learn: 10.9957379	total: 135ms	remaining: 9.51s
14:	learn: 10.7456924	total: 136ms	remaining: 8.9s
15:	learn: 10.5114318	total: 136ms	remaining: 8.37s
16:	learn: 10.2974207	total: 137ms	remaining: 7.9s
17:	learn: 10.0901188	total: 137ms	remaining: 7.48s
18:	learn: 9.9106946	total: 138ms	remaining: 7.11s
19:	learn: 9.7172730	total: 138ms	remaining: 6.77s
20:	learn: 9.5136736	total: 139ms	remaining: 6.46s
21:	learn: 9.3241598	total: 139ms	remaining: 6.19s
22:	learn: 9.1407624	total: 140ms	remaining: 5.93s
23:	learn: 8.9815799	total: 140ms	remaining: 5.7s
24:	learn: 8.8474943	total: 141ms	remaining: 5.48s
25:	learn: 8.7143523	total: 141ms	remaining: 5.29s
26:	learn: 8.5669375	total: 142ms	remaining: 5.11s
27:	learn: 8.4309119	total: 142ms	remaining: 4.94s
28:	learn: 8.2901270	total: 143ms	remaining: 4.79s
29:	learn: 8.1534024	total: 144ms	remaining: 4.64s
30:	learn: 8.0354469	total: 144ms	remaining: 4.5s
31:	learn: 7.9141745	total: 145ms	remaining: 4.38s
32:	learn: 7.8080124	total: 145ms	remaining: 4.25s
33:	learn: 7.7042329	total: 146ms	remaining: 4.14s
34:	learn: 7.6054192	total: 146ms	remaining: 4.03s
35:	learn: 7.5033728	total: 147ms	remaining: 3.93s
36:	learn: 7.4123602	total: 147ms	remaining: 3.83s
37:	learn: 7.3205400	total: 148ms	remaining: 3.74s
38:	learn: 7.2387384	total: 148ms	remaining: 3.66s
39:	learn: 7.1432540	total: 149ms	remaining: 3.58s
40:	learn: 7.0551730	total: 150ms	remaining: 3.5s
41:	learn: 6.9812265	total: 150ms	remaining: 3.42s
42:	learn: 6.9285916	total: 151ms	remaining: 3.35s
43:	learn: 6.8623083	total: 151ms	remaining: 3.28s
44:	learn: 6.7895656	total: 152ms	remaining: 3.22s
45:	learn: 6.7253863	total: 152ms	remaining: 3.15s
46:	learn: 6.6588329	total: 153ms	remaining: 3.1s
47:	learn: 6.5892846	total: 153ms	remaining: 3.04s
48:	learn: 6.5209934	total: 154ms	remaining: 2.98s
49:	learn: 6.4590977	total: 154ms	remaining: 2.93s
50:	learn: 6.4016558	total: 155ms	remaining: 2.88s
51:	learn: 6.3471920	total: 155ms	remaining: 2.83s
52:	learn: 6.3005660	total: 156ms	remaining: 2.79s
53:	learn: 6.2488321	total: 156ms	remaining: 2.74s
54:	learn: 6.1996675	total: 157ms	remaining: 2.7s
55:	learn: 6.1534739	total: 158ms	remaining: 2.66s
56:	learn: 6.1132565	total: 158ms	remaining: 2.62s
57:	learn: 6.0692861	total: 159ms	remaining: 2.58s
58:	learn: 6.0292810	total: 159ms	remaining: 2.54s
59:	learn: 5.9946033	total: 160ms	remaining: 2.5s
60:	learn: 5.9600793	total: 160ms	remaining: 2.47s
61:	learn: 5.9253323	total: 161ms	remaining: 2.43s
62:	learn: 5.8895165	total: 161ms	remaining: 2.4s
63:	learn: 5.8542497	total: 162ms	remaining: 2.37s
64:	learn: 5.8269227	total: 162ms	remaining: 2.34s
65:	learn: 5.7961009	total: 163ms	remaining: 2.31s
66:	learn: 5.7650111	total: 163ms	remaining: 2.28s
67:	learn: 5.7354633	total: 164ms	remaining: 2.25s
68:	learn: 5.7116585	total: 165ms	remaining: 2.22s
69:	learn: 5.6864478	total: 165ms	remaining: 2.19s
70:	learn: 5.6629335	total: 166ms	remaining: 2.17s
71:	learn: 5.6398008	total: 166ms	remaining: 2.14s
72:	learn: 5.6152288	total: 167ms	remaining: 2.12s
73:	learn: 5.5893499	total: 167ms	remaining: 2.09s
74:	learn: 5.5657517	total: 168ms	remaining: 2.07s
75:	learn: 5.5443358	total: 168ms	remaining: 2.04s
76:	learn: 5.5170970	total: 169ms	remaining: 2.02s
77:	learn: 5.4954553	total: 169ms	remaining: 2s
78:	learn: 5.4753900	total: 170ms	remaining: 1.98s
79:	learn: 5.4514204	total: 170ms	remaining: 1.96s
80:	learn: 5.4335485	total: 171ms	remaining: 1.94s
81:	learn: 5.4141915	total: 172ms	remaining: 1.92s
82:	learn: 5.4003472	total: 172ms	remaining: 1.9s
83:	learn: 5.3831638	total: 173ms	remaining: 1.88s
84:	learn: 5.3668989	total: 173ms	remaining: 1.86s
85:	learn: 5.3554238	total: 174ms	remaining: 1.85s
86:	learn: 5.3422956	total: 174ms	remaining: 1.83s
87:	learn: 5.3298419	total: 175ms	remaining: 1.81s
88:	learn: 5.3148321	total: 175ms	remaining: 1.79s
89:	learn: 5.3034084	total: 176ms	remaining: 1.78s
90:	learn: 5.2921971	total: 176ms	remaining: 1.76s
91:	learn: 5.2824718	total: 177ms	remaining: 1.75s
92:	learn: 5.2688968	total: 177ms	remaining: 1.73s
93:	learn: 5.2542259	total: 178ms	remaining: 1.71s
94:	learn: 5.2415765	total: 178ms	remaining: 1.7s
95:	learn: 5.2282635	total: 179ms	remaining: 1.69s
96:	learn: 5.2173397	total: 179ms	remaining: 1.67s
97:	learn: 5.2071426	total: 180ms	remaining: 1.66s
98:	learn: 5.1969417	total: 181ms	remaining: 1.64s
99:	learn: 5.1876575	total: 181ms	remaining: 1.63s
100:	learn: 5.1781534	total: 182ms	remaining: 1.62s
101:	learn: 5.1674000	total: 182ms	remaining: 1.6s
102:	learn: 5.1592481	total: 183ms	remaining: 1.59s
103:	learn: 5.1517672	total: 183ms	remaining: 1.58s
104:	learn: 5.1409138	total: 184ms	remaining: 1.56s
105:	learn: 5.1314151	total: 184ms	remaining: 1.55s
106:	learn: 5.1239221	total: 185ms	remaining: 1.54s
107:	learn: 5.1187234	total: 185ms	remaining: 1.53s
108:	learn: 5.1111802	total: 186ms	remaining: 1.52s
109:	learn: 5.1033027	total: 186ms	remaining: 1.51s
110:	learn: 5.0939847	total: 187ms	remaining: 1.5s
111:	learn: 5.0865786	total: 187ms	remaining: 1.49s
112:	learn: 5.0798506	total: 188ms	remaining: 1.47s
113:	learn: 5.0714757	total: 188ms	remaining: 1.46s
114:	learn: 5.0634801	total: 189ms	remaining: 1.45s
115:	learn: 5.0541375	total: 189ms	remaining: 1.44s
116:	learn: 5.0451686	total: 190ms	remaining: 1.43s
117:	learn: 5.0401685	total: 191ms	remaining: 1.42s
118:	learn: 5.0309477	total: 191ms	remaining: 1.41s
119:	learn: 5.0262451	total: 192ms	remaining: 1.41s
120:	learn: 5.0198726	total: 192ms	remaining: 1.4s
121:	learn: 5.0137076	total: 193ms	remaining: 1.39s
122:	learn: 5.0071876	total: 193ms	remaining: 1.38s
123:	learn: 5.0023957	total: 194ms	remaining: 1.37s
124:	learn: 4.9950130	total: 194ms	remaining: 1.36s
125:	learn: 4.9911813	total: 195ms	remaining: 1.35s
126:	learn: 4.9874989	total: 195ms	remaining: 1.34s
127:	learn: 4.9845209	total: 196ms	remaining: 1.33s
128:	learn: 4.9788171	total: 196ms	remaining: 1.32s
129:	learn: 4.9732564	total: 197ms	remaining: 1.32s
130:	learn: 4.9701452	total: 197ms	remaining: 1.31s
131:	learn: 4.9652034	total: 198ms	remaining: 1.3s
132:	learn: 4.9618234	total: 199ms	remaining: 1.29s
133:	learn: 4.9586222	total: 199ms	remaining: 1.28s
134:	learn: 4.9548190	total: 200ms	remaining: 1.28s
135:	learn: 4.9492377	total: 200ms	remaining: 1.27s
136:	learn: 4.9440501	total: 201ms	remaining: 1.26s
137:	learn: 4.9404313	total: 201ms	remaining: 1.26s
138:	learn: 4.9352480	total: 202ms	remaining: 1.25s
139:	learn: 4.9298283	total: 203ms	remaining: 1.24s
140:	learn: 4.9254687	total: 203ms	remaining: 1.24s
141:	learn: 4.9234599	total: 204ms	remaining: 1.23s
142:	learn: 4.9195680	total: 204ms	remaining: 1.22s
143:	learn: 4.9111872	total: 205ms	remaining: 1.22s
144:	learn: 4.9068255	total: 205ms	remaining: 1.21s
145:	learn: 4.9004692	total: 206ms	remaining: 1.2s
146:	learn: 4.8952941	total: 206ms	remaining: 1.2s
147:	learn: 4.8932405	total: 207ms	remaining: 1.19s
148:	learn: 4.8892520	total: 207ms	remaining: 1.18s
149:	learn: 4.8860818	total: 208ms	remaining: 1.18s
150:	learn: 4.8825518	total: 209ms	remaining: 1.17s
151:	learn: 4.8797422	total: 209ms	remaining: 1.17s
152:	learn: 4.8741349	total: 210ms	remaining: 1.16s
153:	learn: 4.8727362	total: 210ms	remaining: 1.15s
154:	learn: 4.8693383	total: 210ms	remaining: 1.15s
155:	learn: 4.8629673	total: 211ms	remaining: 1.14s
156:	learn: 4.8585432	total: 212ms	remaining: 1.14s
157:	learn: 4.8566362	total: 212ms	remaining: 1.13s
158:	learn: 4.8526202	total: 213ms	remaining: 1.13s
159:	learn: 4.8496452	total: 213ms	remaining: 1.12s
160:	learn: 4.8455912	total: 214ms	remaining: 1.11s
161:	learn: 4.8433849	total: 214ms	remaining: 1.11s
162:	learn: 4.8382781	total: 215ms	remaining: 1.1s
163:	learn: 4.8353881	total: 216ms	remaining: 1.1s
164:	learn: 4.8350929	total: 216ms	remaining: 1.09s
165:	learn: 4.8290253	total: 216ms	remaining: 1.09s
166:	learn: 4.8261730	total: 217ms	remaining: 1.08s
167:	learn: 4.8234238	total: 217ms	remaining: 1.08s
168:	learn: 4.8189639	total: 218ms	remaining: 1.07s
169:	learn: 4.8150263	total: 219ms	remaining: 1.07s
170:	learn: 4.8140267	total: 219ms	remaining: 1.06s
171:	learn: 4.8117463	total: 220ms	remaining: 1.06s
172:	learn: 4.8078712	total: 220ms	remaining: 1.05s
173:	learn: 4.8018318	total: 221ms	remaining: 1.05s
174:	learn: 4.7970140	total: 221ms	remaining: 1.04s
175:	learn: 4.7919210	total: 222ms	remaining: 1.04s
176:	learn: 4.7889408	total: 222ms	remaining: 1.03s
177:	learn: 4.7854033	total: 223ms	remaining: 1.03s
178:	learn: 4.7835712	total: 223ms	remaining: 1.02s
179:	learn: 4.7808219	total: 224ms	remaining: 1.02s
180:	learn: 4.7774292	total: 225ms	remaining: 1.01s
181:	learn: 4.7738034	total: 225ms	remaining: 1.01s
182:	learn: 4.7708604	total: 226ms	remaining: 1.01s
183:	learn: 4.7662307	total: 226ms	remaining: 1s
184:	learn: 4.7633432	total: 227ms	remaining: 999ms
185:	learn: 4.7579134	total: 227ms	remaining: 994ms
186:	learn: 4.7538805	total: 228ms	remaining: 990ms
187:	learn: 4.7495477	total: 228ms	remaining: 987ms
188:	learn: 4.7473019	total: 229ms	remaining: 983ms
189:	learn: 4.7440515	total: 230ms	remaining: 979ms
190:	learn: 4.7409163	total: 230ms	remaining: 975ms
191:	learn: 4.7377375	total: 231ms	remaining: 971ms
192:	learn: 4.7350963	total: 231ms	remaining: 967ms
193:	learn: 4.7330283	total: 232ms	remaining: 963ms
194:	learn: 4.7263117	total: 232ms	remaining: 959ms
195:	learn: 4.7228226	total: 233ms	remaining: 955ms
196:	learn: 4.7200499	total: 233ms	remaining: 951ms
197:	learn: 4.7167573	total: 234ms	remaining: 947ms
198:	learn: 4.7146277	total: 234ms	remaining: 944ms
199:	learn: 4.7116965	total: 235ms	remaining: 940ms
200:	learn: 4.7052132	total: 236ms	remaining: 936ms
201:	learn: 4.7027121	total: 236ms	remaining: 933ms
202:	learn: 4.7003624	total: 237ms	remaining: 929ms
203:	learn: 4.6984420	total: 237ms	remaining: 925ms
204:	learn: 4.6939955	total: 238ms	remaining: 921ms
205:	learn: 4.6902719	total: 238ms	remaining: 918ms
206:	learn: 4.6875311	total: 239ms	remaining: 914ms
207:	learn: 4.6851599	total: 239ms	remaining: 911ms
208:	learn: 4.6818163	total: 240ms	remaining: 907ms
209:	learn: 4.6798801	total: 240ms	remaining: 904ms
210:	learn: 4.6763366	total: 241ms	remaining: 900ms
211:	learn: 4.6739259	total: 241ms	remaining: 897ms
212:	learn: 4.6685780	total: 242ms	remaining: 894ms
213:	learn: 4.6656344	total: 242ms	remaining: 891ms
214:	learn: 4.6614506	total: 243ms	remaining: 887ms
215:	learn: 4.6588292	total: 244ms	remaining: 884ms
216:	learn: 4.6561919	total: 244ms	remaining: 881ms
217:	learn: 4.6520584	total: 245ms	remaining: 878ms
218:	learn: 4.6497072	total: 245ms	remaining: 874ms
219:	learn: 4.6474409	total: 246ms	remaining: 871ms
220:	learn: 4.6450639	total: 246ms	remaining: 868ms
221:	learn: 4.6433072	total: 247ms	remaining: 865ms
222:	learn: 4.6409036	total: 247ms	remaining: 861ms
223:	learn: 4.6388937	total: 248ms	remaining: 858ms
224:	learn: 4.6342158	total: 248ms	remaining: 855ms
225:	learn: 4.6297177	total: 249ms	remaining: 852ms
226:	learn: 4.6275298	total: 249ms	remaining: 849ms
227:	learn: 4.6250109	total: 250ms	remaining: 846ms
228:	learn: 4.6229899	total: 250ms	remaining: 843ms
229:	learn: 4.6207206	total: 251ms	remaining: 840ms
230:	learn: 4.6184273	total: 251ms	remaining: 837ms
231:	learn: 4.6147620	total: 252ms	remaining: 834ms
232:	learn: 4.6114308	total: 252ms	remaining: 831ms
233:	learn: 4.6086854	total: 253ms	remaining: 828ms
234:	learn: 4.6035875	total: 254ms	remaining: 825ms
235:	learn: 4.5989914	total: 254ms	remaining: 822ms
236:	learn: 4.5946902	total: 255ms	remaining: 820ms
237:	learn: 4.5927370	total: 255ms	remaining: 817ms
238:	learn: 4.5911938	total: 256ms	remaining: 814ms
239:	learn: 4.5897305	total: 256ms	remaining: 811ms
240:	learn: 4.5852319	total: 257ms	remaining: 808ms
241:	learn: 4.5833489	total: 257ms	remaining: 806ms
242:	learn: 4.5816370	total: 258ms	remaining: 803ms
243:	learn: 4.5794938	total: 258ms	remaining: 800ms
244:	learn: 4.5773249	total: 259ms	remaining: 798ms
245:	learn: 4.5725624	total: 259ms	remaining: 795ms
246:	learn: 4.5711619	total: 260ms	remaining: 792ms
247:	learn: 4.5689159	total: 260ms	remaining: 790ms
248:	learn: 4.5664594	total: 261ms	remaining: 787ms
249:	learn: 4.5653444	total: 262ms	remaining: 785ms
250:	learn: 4.5614371	total: 262ms	remaining: 782ms
251:	learn: 4.5594752	total: 263ms	remaining: 780ms
252:	learn: 4.5580352	total: 263ms	remaining: 777ms
253:	learn: 4.5543859	total: 264ms	remaining: 775ms
254:	learn: 4.5484132	total: 264ms	remaining: 772ms
255:	learn: 4.5470969	total: 265ms	remaining: 770ms
256:	learn: 4.5410687	total: 265ms	remaining: 768ms
257:	learn: 4.5375379	total: 266ms	remaining: 765ms
258:	learn: 4.5326139	total: 267ms	remaining: 763ms
259:	learn: 4.5270095	total: 267ms	remaining: 760ms
260:	learn: 4.5253336	total: 268ms	remaining: 758ms
261:	learn: 4.5196822	total: 268ms	remaining: 756ms
262:	learn: 4.5174815	total: 269ms	remaining: 753ms
263:	learn: 4.5123164	total: 269ms	remaining: 751ms
264:	learn: 4.5090146	total: 270ms	remaining: 749ms
265:	learn: 4.5070414	total: 271ms	remaining: 746ms
266:	learn: 4.5014796	total: 271ms	remaining: 744ms
267:	learn: 4.4963506	total: 272ms	remaining: 742ms
268:	learn: 4.4942142	total: 272ms	remaining: 740ms
269:	learn: 4.4929853	total: 273ms	remaining: 738ms
270:	learn: 4.4891241	total: 273ms	remaining: 735ms
271:	learn: 4.4867457	total: 274ms	remaining: 733ms
272:	learn: 4.4856462	total: 274ms	remaining: 731ms
273:	learn: 4.4822610	total: 275ms	remaining: 729ms
274:	learn: 4.4770245	total: 276ms	remaining: 727ms
275:	learn: 4.4722572	total: 276ms	remaining: 724ms
276:	learn: 4.4705609	total: 277ms	remaining: 722ms
277:	learn: 4.4693878	total: 277ms	remaining: 720ms
278:	learn: 4.4662309	total: 278ms	remaining: 718ms
279:	learn: 4.4619075	total: 278ms	remaining: 716ms
280:	learn: 4.4592790	total: 279ms	remaining: 713ms
281:	learn: 4.4581453	total: 279ms	remaining: 711ms
282:	learn: 4.4530310	total: 280ms	remaining: 709ms
283:	learn: 4.4484990	total: 280ms	remaining: 707ms
284:	learn: 4.4462666	total: 281ms	remaining: 705ms
285:	learn: 4.4449413	total: 282ms	remaining: 703ms
286:	learn: 4.4419400	total: 282ms	remaining: 701ms
287:	learn: 4.4379691	total: 283ms	remaining: 699ms
288:	learn: 4.4335730	total: 283ms	remaining: 697ms
289:	learn: 4.4289195	total: 284ms	remaining: 694ms
290:	learn: 4.4241487	total: 284ms	remaining: 692ms
291:	learn: 4.4228505	total: 285ms	remaining: 690ms
292:	learn: 4.4216964	total: 285ms	remaining: 688ms
293:	learn: 4.4177096	total: 286ms	remaining: 687ms
294:	learn: 4.4114133	total: 286ms	remaining: 685ms
295:	learn: 4.4063388	total: 287ms	remaining: 683ms
296:	learn: 4.4000475	total: 288ms	remaining: 681ms
297:	learn: 4.3961437	total: 288ms	remaining: 679ms
298:	learn: 4.3924774	total: 289ms	remaining: 677ms
299:	learn: 4.3909523	total: 289ms	remaining: 675ms
300:	learn: 4.3873009	total: 290ms	remaining: 673ms
301:	learn: 4.3842159	total: 290ms	remaining: 671ms
302:	learn: 4.3807633	total: 291ms	remaining: 669ms
303:	learn: 4.3798923	total: 291ms	remaining: 667ms
304:	learn: 4.3752429	total: 292ms	remaining: 665ms
305:	learn: 4.3702679	total: 292ms	remaining: 663ms
306:	learn: 4.3678388	total: 293ms	remaining: 661ms
307:	learn: 4.3624072	total: 294ms	remaining: 660ms
308:	learn: 4.3604610	total: 294ms	remaining: 658ms
309:	learn: 4.3574785	total: 295ms	remaining: 656ms
310:	learn: 4.3552596	total: 295ms	remaining: 654ms
311:	learn: 4.3546051	total: 296ms	remaining: 652ms
312:	learn: 4.3524606	total: 296ms	remaining: 650ms
313:	learn: 4.3493483	total: 297ms	remaining: 648ms
314:	learn: 4.3448560	total: 297ms	remaining: 647ms
315:	learn: 4.3446908	total: 298ms	remaining: 645ms
316:	learn: 4.3426121	total: 298ms	remaining: 643ms
317:	learn: 4.3412180	total: 299ms	remaining: 641ms
318:	learn: 4.3391310	total: 300ms	remaining: 640ms
319:	learn: 4.3358611	total: 300ms	remaining: 638ms
320:	learn: 4.3339195	total: 301ms	remaining: 637ms
321:	learn: 4.3283917	total: 302ms	remaining: 635ms
322:	learn: 4.3234128	total: 302ms	remaining: 634ms
323:	learn: 4.3200106	total: 303ms	remaining: 632ms
324:	learn: 4.3189676	total: 304ms	remaining: 630ms
325:	learn: 4.3178556	total: 304ms	remaining: 629ms
326:	learn: 4.3167344	total: 305ms	remaining: 627ms
327:	learn: 4.3130385	total: 305ms	remaining: 626ms
328:	learn: 4.3112541	total: 306ms	remaining: 624ms
329:	learn: 4.3090675	total: 307ms	remaining: 622ms
330:	learn: 4.3069726	total: 307ms	remaining: 621ms
331:	learn: 4.3047731	total: 308ms	remaining: 619ms
332:	learn: 4.2999724	total: 308ms	remaining: 617ms
333:	learn: 4.2965036	total: 309ms	remaining: 616ms
334:	learn: 4.2923391	total: 309ms	remaining: 614ms
335:	learn: 4.2888641	total: 310ms	remaining: 612ms
336:	learn: 4.2869795	total: 310ms	remaining: 611ms
337:	learn: 4.2839011	total: 311ms	remaining: 609ms
338:	learn: 4.2826754	total: 312ms	remaining: 608ms
339:	learn: 4.2813198	total: 313ms	remaining: 607ms
340:	learn: 4.2775990	total: 313ms	remaining: 605ms
341:	learn: 4.2768073	total: 314ms	remaining: 604ms
342:	learn: 4.2743496	total: 314ms	remaining: 602ms
343:	learn: 4.2712772	total: 315ms	remaining: 601ms
344:	learn: 4.2688991	total: 315ms	remaining: 599ms
345:	learn: 4.2652098	total: 316ms	remaining: 597ms
346:	learn: 4.2605198	total: 317ms	remaining: 596ms
347:	learn: 4.2561855	total: 317ms	remaining: 594ms
348:	learn: 4.2529480	total: 318ms	remaining: 593ms
349:	learn: 4.2478474	total: 318ms	remaining: 591ms
350:	learn: 4.2468073	total: 319ms	remaining: 590ms
351:	learn: 4.2425478	total: 319ms	remaining: 588ms
352:	learn: 4.2397277	total: 320ms	remaining: 587ms
353:	learn: 4.2378657	total: 321ms	remaining: 585ms
354:	learn: 4.2339600	total: 321ms	remaining: 583ms
355:	learn: 4.2328737	total: 322ms	remaining: 582ms
356:	learn: 4.2309180	total: 322ms	remaining: 580ms
357:	learn: 4.2294626	total: 323ms	remaining: 579ms
358:	learn: 4.2281459	total: 323ms	remaining: 577ms
359:	learn: 4.2262705	total: 324ms	remaining: 576ms
360:	learn: 4.2244193	total: 324ms	remaining: 574ms
361:	learn: 4.2204369	total: 325ms	remaining: 573ms
362:	learn: 4.2153563	total: 326ms	remaining: 571ms
363:	learn: 4.2140452	total: 326ms	remaining: 570ms
364:	learn: 4.2126369	total: 327ms	remaining: 568ms
365:	learn: 4.2111850	total: 327ms	remaining: 567ms
366:	learn: 4.2069542	total: 328ms	remaining: 566ms
367:	learn: 4.2043920	total: 329ms	remaining: 565ms
368:	learn: 4.2035851	total: 329ms	remaining: 563ms
369:	learn: 4.1991259	total: 330ms	remaining: 562ms
370:	learn: 4.1973204	total: 330ms	remaining: 560ms
371:	learn: 4.1927208	total: 331ms	remaining: 559ms
372:	learn: 4.1894965	total: 332ms	remaining: 557ms
373:	learn: 4.1875316	total: 332ms	remaining: 556ms
374:	learn: 4.1827504	total: 333ms	remaining: 555ms
375:	learn: 4.1793648	total: 333ms	remaining: 553ms
376:	learn: 4.1749363	total: 334ms	remaining: 552ms
377:	learn: 4.1731861	total: 334ms	remaining: 550ms
378:	learn: 4.1684303	total: 335ms	remaining: 549ms
379:	learn: 4.1677937	total: 335ms	remaining: 547ms
380:	learn: 4.1627160	total: 336ms	remaining: 546ms
381:	learn: 4.1621090	total: 337ms	remaining: 544ms

In [19]:
eval_metrics.sort_values(by='test_r2', ascending=False)

,train_mse,train_mae,train_r2,test_mse,test_mae,test_r2
Ridge,27.808008,4.193683,0.882193,31.173279,4.473882,0.847351
Linear Regression,27.802890,4.194622,0.882215,31.229441,4.474701,0.847076
Random Forest,5.065172,1.797051,0.978542,38.853560,4.909846,0.809742
Ada Boost,32.435798,4.615912,0.862588,38.878542,4.957756,0.809619
Catboost,9.269073,2.358293,0.960732,39.701589,5.107573,0.805589
SVR,48.279530,5.193324,0.795467,42.236121,5.045050,0.793178
Lasso,42.719545,5.173179,0.819022,43.355863,5.159657,0.787695
Xgboost,0.889402,0.624058,0.996232,44.862415,5.359961,0.780317
K Neighbors,33.392100,4.570500,0.858537,48.987400,5.651000,0.760118
Decision Tree,0.015625,0.006250,0.999934,71.055000,6.855000,0.652057