In [307]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [308]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.svm import SVR
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

## 1. Load dataset

In [309]:
df = pd.read_csv('data/student.csv')
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [310]:
X = df.drop(columns=['math_score'])
y = df['math_score']

## 2. Train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [312]:
X_train.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'reading_score', 'writing_score'],
      dtype='str')

## 3. Feature groups

In [313]:
numeric_features = X_train.select_dtypes(exclude=['object', 'string']).columns.tolist()
categorical_features = X_train.select_dtypes(include=['object', 'string']).columns.tolist()
print(f"Numeric features: {numeric_features}")
print(f"categorical features: {categorical_features}")

Numeric features: ['reading_score', 'writing_score']
categorical features: ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

In [314]:
X_train['parental_level_of_education'].unique()

<StringArray>
[      'some college',        'high school',  'bachelor's degree',
 'associate's degree',   'some high school',    'master's degree']
Length: 6, dtype: str

In [315]:
ordinal_features = ['parental_level_of_education']
education_order = ['some high school', 'high school', 'some college', "associate's degree", "bachelor's degree", "master's degree"]
nominal_features = [col for col in categorical_features if col not in ordinal_features]

In [316]:
print(f"Nominal features: {nominal_features}")

Nominal features: ['gender', 'race_ethnicity', 'lunch', 'test_preparation_course']

## 4. Pipelines per feature type

In [317]:
numeric_pipeline = Pipeline([('imputer', SimpleImputer(strategy='mean')), ('scaler', StandardScaler())])
nominal_pipeline = Pipeline([('imputer', SimpleImputer(strategy='most_frequent')), ('encoder', OneHotEncoder(handle_unknown="ignore", drop='first', sparse_output=True))])
ordinal_pipeline = Pipeline([('imputer', SimpleImputer(strategy='most_frequent')), ('encoder', OrdinalEncoder(categories=[education_order], handle_unknown="use_encoded_value", unknown_value=-1))])

In [318]:
preprocessing = ColumnTransformer([('numeric', numeric_pipeline, numeric_features), ('nominal', nominal_pipeline, nominal_features), ('ordinal', ordinal_pipeline, ordinal_features)])

## 5. Full pipeline with model

In [319]:
model = LinearRegression()

model_pipeline = Pipeline([('preprocessing', preprocessing), ('model', model)])

## 6. Fit the model

In [320]:
model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['reading_score',
                                                   'writing_score']),
                                                 ('nominal',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['gender', 'race_ethn...
                                                 ('ordinal',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['some '
                                                                                               'high '
                                                                                               'school',
                                                                                               'high '
                                                                                               'school',
                                                                                               'some '
                                                                                               'college',
                                                                                               "associate's "
                                                                                               'degree',
                                                                                               "bachelor's "
                                                                                               'degree',
                                                                                               "master's "
                                                                                               'degree']],
                                                                                  handle_unknown='use_encoded_value',
                                                                                  unknown_value=-1))]),
                                                  ['parental_level_of_education'])])),
                ('model', LinearRegression())])

## 7. Model evaluation on test set

In [321]:
def evaluate_model(X, y):
    y_pred = model_pipeline.predict(X)
    mse = mean_squared_error(y, y_pred)
    mae = mean_absolute_error(y, y_pred)
    r2 = r2_score(y, y_pred)
    return mse, mae, r2

## 8. Testing various models

In [322]:
models = {'Linear Regression': LinearRegression(),
'Lasso': Lasso(),
'Ridge': Ridge(),
'Decision Tree': DecisionTreeRegressor(),
'Random Forest': RandomForestRegressor(),
'Ada Boost': AdaBoostRegressor(),
'K Neighbors': KNeighborsRegressor(),
'SVR': SVR(),
'Catboost': CatBoostRegressor(),
'Xgboost': XGBRegressor()}

In [323]:
eval_metrics = pd.DataFrame(np.nan, index=models.keys(), columns=['train_mse', 'train_mae', 'train_r2', 'test_mse', 'test_mae', 'test_r2'])

In [ ]:
for k, v in models.items():
    model_pipeline = Pipeline([('preprocessing', preprocessing), ('model', v)])
    model_pipeline.fit(X_train, y_train)
    print(f"Training Model: {k}\n")
    mse, mae, r2 = evaluate_model(X_train, y_train)
    eval_metrics.loc[k, 'train_mse'] = mse
    eval_metrics.loc[k, 'train_mae'] = mae
    eval_metrics.loc[k, 'train_r2'] = r2

    mse, mae, r2 = evaluate_model(X_test, y_test)
    eval_metrics.loc[k, 'test_mse'] = mse
    eval_metrics.loc[k, 'test_mae'] = mae
    eval_metrics.loc[k, 'test_r2'] = r2

--------------------------------------
Training Model: Linear Regression

Training Model: Lasso

Training Model: Ridge

Training Model: Decision Tree

Training Model: Random Forest

Training Model: Ada Boost

Training Model: K Neighbors

Training Model: SVR

Learning rate set to 0.039525
0:	learn: 14.8954029	total: 693us	remaining: 693ms
1:	learn: 14.4902512	total: 1.28ms	remaining: 637ms
2:	learn: 14.1379395	total: 1.85ms	remaining: 615ms
3:	learn: 13.7786087	total: 2.42ms	remaining: 603ms
4:	learn: 13.4038297	total: 2.96ms	remaining: 590ms
5:	learn: 13.0629579	total: 3.51ms	remaining: 582ms
6:	learn: 12.7899288	total: 4.11ms	remaining: 583ms
7:	learn: 12.4866870	total: 4.67ms	remaining: 579ms
8:	learn: 12.1688985	total: 5.23ms	remaining: 576ms
9:	learn: 11.8586294	total: 5.77ms	remaining: 571ms
10:	learn: 11.5823901	total: 6.33ms	remaining: 569ms
11:	learn: 11.3122489	total: 6.89ms	remaining: 567ms
12:	learn: 11.1062482	total: 7.46ms	remaining: 566ms
13:	learn: 10.8916023	total: 8ms	remaining: 563ms
14:	learn: 10.6551164	total: 8.53ms	remaining: 560ms
15:	learn: 10.4481360	total: 9.08ms	remaining: 558ms
16:	learn: 10.2357931	total: 9.64ms	remaining: 557ms
17:	learn: 10.0470971	total: 10.2ms	remaining: 556ms
18:	learn: 9.8389738	total: 10.8ms	remaining: 555ms
19:	learn: 9.6571405	total: 11.4ms	remaining: 559ms
20:	learn: 9.4891611	total: 12ms	remaining: 558ms
21:	learn: 9.3061420	total: 12.5ms	remaining: 558ms
22:	learn: 9.1487393	total: 13ms	remaining: 552ms
23:	learn: 8.9966152	total: 13.6ms	remaining: 552ms
24:	learn: 8.8449572	total: 14.1ms	remaining: 551ms
25:	learn: 8.6985074	total: 14.7ms	remaining: 550ms
26:	learn: 8.5459080	total: 15.2ms	remaining: 549ms
27:	learn: 8.4018842	total: 15.8ms	remaining: 547ms
28:	learn: 8.2552571	total: 16.3ms	remaining: 546ms
29:	learn: 8.1233805	total: 16.9ms	remaining: 545ms
30:	learn: 7.9873192	total: 17.4ms	remaining: 545ms
31:	learn: 7.8664033	total: 18ms	remaining: 544ms
32:	learn: 7.7730379	total: 18.5ms	remaining: 543ms
33:	learn: 7.6637354	total: 19.1ms	remaining: 542ms
34:	learn: 7.5575697	total: 19.6ms	remaining: 541ms
35:	learn: 7.4586479	total: 20.2ms	remaining: 540ms
36:	learn: 7.3608977	total: 20.7ms	remaining: 539ms
37:	learn: 7.2775704	total: 21.3ms	remaining: 539ms
38:	learn: 7.1899803	total: 21.9ms	remaining: 539ms
39:	learn: 7.1131360	total: 22.4ms	remaining: 539ms
40:	learn: 7.0275574	total: 23ms	remaining: 538ms
41:	learn: 6.9538089	total: 23.5ms	remaining: 537ms
42:	learn: 6.8879921	total: 24.1ms	remaining: 536ms
43:	learn: 6.8231692	total: 24.6ms	remaining: 535ms
44:	learn: 6.7605638	total: 25.2ms	remaining: 534ms
45:	learn: 6.6880686	total: 25.7ms	remaining: 534ms
46:	learn: 6.6256629	total: 26.3ms	remaining: 533ms
47:	learn: 6.5579533	total: 26.8ms	remaining: 532ms
48:	learn: 6.5124813	total: 27.2ms	remaining: 528ms
49:	learn: 6.4601894	total: 27.7ms	remaining: 527ms
50:	learn: 6.4088387	total: 28.2ms	remaining: 525ms
51:	learn: 6.3778886	total: 28.6ms	remaining: 521ms
52:	learn: 6.3227055	total: 29.1ms	remaining: 520ms
53:	learn: 6.2738280	total: 29.7ms	remaining: 520ms
54:	learn: 6.2299422	total: 30.2ms	remaining: 519ms
55:	learn: 6.1868792	total: 30.8ms	remaining: 519ms
56:	learn: 6.1374272	total: 31.3ms	remaining: 518ms
57:	learn: 6.0958578	total: 31.8ms	remaining: 517ms
58:	learn: 6.0614807	total: 32.4ms	remaining: 516ms
59:	learn: 6.0262060	total: 32.9ms	remaining: 516ms
60:	learn: 5.9904674	total: 33.5ms	remaining: 515ms
61:	learn: 5.9623438	total: 34ms	remaining: 514ms
62:	learn: 5.9284440	total: 34.5ms	remaining: 513ms
63:	learn: 5.8926976	total: 35.1ms	remaining: 513ms
64:	learn: 5.8692399	total: 35.7ms	remaining: 513ms
65:	learn: 5.8360020	total: 36.2ms	remaining: 513ms
66:	learn: 5.8137278	total: 36.8ms	remaining: 513ms
67:	learn: 5.7882829	total: 37.3ms	remaining: 512ms
68:	learn: 5.7618340	total: 37.9ms	remaining: 511ms
69:	learn: 5.7383151	total: 38.4ms	remaining: 511ms
70:	learn: 5.7176459	total: 39ms	remaining: 510ms
71:	learn: 5.6950701	total: 39.5ms	remaining: 509ms
72:	learn: 5.6730253	total: 40.1ms	remaining: 509ms
73:	learn: 5.6520939	total: 40.7ms	remaining: 509ms
74:	learn: 5.6345279	total: 41ms	remaining: 506ms
75:	learn: 5.6158537	total: 41.5ms	remaining: 505ms
76:	learn: 5.5973756	total: 42.1ms	remaining: 505ms
77:	learn: 5.5799163	total: 42.6ms	remaining: 504ms
78:	learn: 5.5622883	total: 43.2ms	remaining: 503ms
79:	learn: 5.5434863	total: 43.7ms	remaining: 503ms
80:	learn: 5.5249398	total: 44.2ms	remaining: 502ms
81:	learn: 5.5044761	total: 44.8ms	remaining: 501ms
82:	learn: 5.4882819	total: 45.3ms	remaining: 501ms
83:	learn: 5.4720768	total: 45.8ms	remaining: 500ms
84:	learn: 5.4610307	total: 46.3ms	remaining: 499ms
85:	learn: 5.4492183	total: 46.9ms	remaining: 498ms
86:	learn: 5.4342187	total: 47.4ms	remaining: 498ms
87:	learn: 5.4203751	total: 48ms	remaining: 497ms
88:	learn: 5.4086423	total: 48.5ms	remaining: 496ms
89:	learn: 5.3941299	total: 49ms	remaining: 496ms
90:	learn: 5.3824964	total: 49.6ms	remaining: 495ms
91:	learn: 5.3667776	total: 50.1ms	remaining: 495ms
92:	learn: 5.3569759	total: 50.7ms	remaining: 494ms
93:	learn: 5.3481930	total: 51.2ms	remaining: 493ms
94:	learn: 5.3382135	total: 51.7ms	remaining: 493ms
95:	learn: 5.3309447	total: 52.3ms	remaining: 492ms
96:	learn: 5.3234215	total: 52.8ms	remaining: 492ms
97:	learn: 5.3115735	total: 53.5ms	remaining: 492ms
98:	learn: 5.3048584	total: 53.9ms	remaining: 491ms
99:	learn: 5.2945246	total: 54.4ms	remaining: 490ms
100:	learn: 5.2818532	total: 55ms	remaining: 489ms
101:	learn: 5.2735725	total: 55.5ms	remaining: 489ms
102:	learn: 5.2651917	total: 56ms	remaining: 488ms
103:	learn: 5.2533779	total: 56.6ms	remaining: 488ms
104:	learn: 5.2421128	total: 57.1ms	remaining: 487ms
105:	learn: 5.2318626	total: 57.7ms	remaining: 486ms
106:	learn: 5.2251686	total: 58.2ms	remaining: 486ms
107:	learn: 5.2175371	total: 58.8ms	remaining: 486ms
108:	learn: 5.2092067	total: 59.3ms	remaining: 485ms
109:	learn: 5.2007587	total: 59.9ms	remaining: 484ms
110:	learn: 5.1921737	total: 60.4ms	remaining: 484ms
111:	learn: 5.1852331	total: 60.9ms	remaining: 483ms
112:	learn: 5.1769951	total: 61.5ms	remaining: 482ms
113:	learn: 5.1672308	total: 62ms	remaining: 482ms
114:	learn: 5.1622236	total: 62.5ms	remaining: 481ms
115:	learn: 5.1552618	total: 63.1ms	remaining: 481ms
116:	learn: 5.1485129	total: 63.6ms	remaining: 480ms
117:	learn: 5.1437683	total: 64.2ms	remaining: 480ms
118:	learn: 5.1389747	total: 64.8ms	remaining: 479ms
119:	learn: 5.1324706	total: 65.3ms	remaining: 479ms
120:	learn: 5.1256601	total: 65.8ms	remaining: 478ms
121:	learn: 5.1196158	total: 66.4ms	remaining: 478ms
122:	learn: 5.1143486	total: 66.9ms	remaining: 477ms
123:	learn: 5.1076810	total: 67.5ms	remaining: 477ms
124:	learn: 5.0945594	total: 68ms	remaining: 476ms
125:	learn: 5.0925814	total: 68.3ms	remaining: 474ms
126:	learn: 5.0894457	total: 68.7ms	remaining: 472ms
127:	learn: 5.0845855	total: 69.2ms	remaining: 472ms
128:	learn: 5.0780255	total: 69.8ms	remaining: 471ms
129:	learn: 5.0748971	total: 70.3ms	remaining: 470ms
130:	learn: 5.0658629	total: 70.8ms	remaining: 470ms
131:	learn: 5.0610190	total: 71.4ms	remaining: 469ms
132:	learn: 5.0569982	total: 72ms	remaining: 469ms
133:	learn: 5.0503028	total: 72.5ms	remaining: 469ms
134:	learn: 5.0475000	total: 72.9ms	remaining: 467ms
135:	learn: 5.0418725	total: 73.5ms	remaining: 467ms
136:	learn: 5.0383207	total: 74ms	remaining: 466ms
137:	learn: 5.0340531	total: 74.5ms	remaining: 465ms
138:	learn: 5.0284668	total: 75ms	remaining: 465ms
139:	learn: 5.0247408	total: 75.6ms	remaining: 464ms
140:	learn: 5.0188879	total: 76.1ms	remaining: 464ms
141:	learn: 5.0130829	total: 76.7ms	remaining: 463ms
142:	learn: 5.0081525	total: 77.2ms	remaining: 463ms
143:	learn: 5.0040060	total: 77.7ms	remaining: 462ms
144:	learn: 4.9969994	total: 78.3ms	remaining: 462ms
145:	learn: 4.9939257	total: 78.8ms	remaining: 461ms
146:	learn: 4.9868225	total: 79.4ms	remaining: 461ms
147:	learn: 4.9817361	total: 79.9ms	remaining: 460ms
148:	learn: 4.9782394	total: 80.4ms	remaining: 459ms
149:	learn: 4.9736894	total: 81ms	remaining: 459ms
150:	learn: 4.9683914	total: 81.5ms	remaining: 458ms
151:	learn: 4.9626895	total: 82ms	remaining: 458ms
152:	learn: 4.9566335	total: 82.6ms	remaining: 457ms
153:	learn: 4.9524162	total: 83.2ms	remaining: 457ms
154:	learn: 4.9509723	total: 83.5ms	remaining: 455ms
155:	learn: 4.9475131	total: 84.1ms	remaining: 455ms
156:	learn: 4.9445930	total: 84.6ms	remaining: 454ms
157:	learn: 4.9403644	total: 85.1ms	remaining: 454ms
158:	learn: 4.9369247	total: 85.7ms	remaining: 453ms
159:	learn: 4.9319485	total: 86.2ms	remaining: 453ms
160:	learn: 4.9282587	total: 86.7ms	remaining: 452ms
161:	learn: 4.9239131	total: 87.2ms	remaining: 451ms
162:	learn: 4.9224291	total: 87.8ms	remaining: 451ms
163:	learn: 4.9194892	total: 88.3ms	remaining: 450ms
164:	learn: 4.9138147	total: 88.9ms	remaining: 450ms
165:	learn: 4.9090793	total: 89.4ms	remaining: 449ms
166:	learn: 4.9044192	total: 89.9ms	remaining: 448ms
167:	learn: 4.9004791	total: 90.4ms	remaining: 448ms
168:	learn: 4.8982716	total: 91ms	remaining: 447ms
169:	learn: 4.8922733	total: 91.5ms	remaining: 447ms
170:	learn: 4.8874282	total: 92.1ms	remaining: 447ms
171:	learn: 4.8869404	total: 92.5ms	remaining: 445ms
172:	learn: 4.8817755	total: 93ms	remaining: 445ms
173:	learn: 4.8802150	total: 93.6ms	remaining: 444ms
174:	learn: 4.8748027	total: 94.2ms	remaining: 444ms
175:	learn: 4.8711743	total: 94.7ms	remaining: 444ms
176:	learn: 4.8674275	total: 95.4ms	remaining: 443ms
177:	learn: 4.8640898	total: 96ms	remaining: 443ms
178:	learn: 4.8620222	total: 96.5ms	remaining: 443ms
179:	learn: 4.8592092	total: 97.1ms	remaining: 442ms
180:	learn: 4.8556667	total: 97.6ms	remaining: 442ms
181:	learn: 4.8524514	total: 98.2ms	remaining: 441ms
182:	learn: 4.8488784	total: 98.7ms	remaining: 441ms
183:	learn: 4.8458183	total: 99.3ms	remaining: 440ms
184:	learn: 4.8415088	total: 99.8ms	remaining: 440ms
185:	learn: 4.8371025	total: 100ms	remaining: 439ms
186:	learn: 4.8349100	total: 101ms	remaining: 439ms
187:	learn: 4.8315366	total: 101ms	remaining: 438ms
188:	learn: 4.8257057	total: 102ms	remaining: 437ms
189:	learn: 4.8241843	total: 102ms	remaining: 437ms
190:	learn: 4.8217715	total: 103ms	remaining: 436ms
191:	learn: 4.8177221	total: 104ms	remaining: 436ms
192:	learn: 4.8152629	total: 104ms	remaining: 435ms
193:	learn: 4.8131695	total: 105ms	remaining: 434ms
194:	learn: 4.8099995	total: 105ms	remaining: 434ms
195:	learn: 4.8057217	total: 106ms	remaining: 433ms
196:	learn: 4.8035116	total: 106ms	remaining: 433ms
197:	learn: 4.8002182	total: 107ms	remaining: 432ms
198:	learn: 4.7990744	total: 107ms	remaining: 431ms
199:	learn: 4.7948438	total: 108ms	remaining: 431ms
200:	learn: 4.7895122	total: 108ms	remaining: 431ms
201:	learn: 4.7881349	total: 109ms	remaining: 430ms
202:	learn: 4.7835536	total: 109ms	remaining: 430ms
203:	learn: 4.7828239	total: 110ms	remaining: 429ms
204:	learn: 4.7795733	total: 111ms	remaining: 429ms
205:	learn: 4.7754535	total: 111ms	remaining: 428ms
206:	learn: 4.7717301	total: 112ms	remaining: 428ms
207:	learn: 4.7681136	total: 112ms	remaining: 427ms
208:	learn: 4.7644969	total: 113ms	remaining: 427ms
209:	learn: 4.7596223	total: 113ms	remaining: 426ms
210:	learn: 4.7569757	total: 114ms	remaining: 426ms
211:	learn: 4.7538375	total: 114ms	remaining: 425ms
212:	learn: 4.7531142	total: 115ms	remaining: 425ms
213:	learn: 4.7500869	total: 116ms	remaining: 424ms
214:	learn: 4.7470959	total: 116ms	remaining: 424ms
215:	learn: 4.7451895	total: 117ms	remaining: 424ms
216:	learn: 4.7418542	total: 117ms	remaining: 423ms
217:	learn: 4.7397999	total: 118ms	remaining: 423ms
218:	learn: 4.7380760	total: 118ms	remaining: 422ms
219:	learn: 4.7329365	total: 119ms	remaining: 422ms
220:	learn: 4.7300012	total: 120ms	remaining: 421ms
221:	learn: 4.7266640	total: 120ms	remaining: 421ms
222:	learn: 4.7225651	total: 121ms	remaining: 420ms
223:	learn: 4.7184165	total: 121ms	remaining: 420ms
224:	learn: 4.7139024	total: 122ms	remaining: 420ms
225:	learn: 4.7120965	total: 122ms	remaining: 419ms
226:	learn: 4.7105123	total: 123ms	remaining: 419ms
227:	learn: 4.7078969	total: 123ms	remaining: 418ms
228:	learn: 4.7049939	total: 124ms	remaining: 417ms
229:	learn: 4.6977780	total: 125ms	remaining: 417ms
230:	learn: 4.6954171	total: 125ms	remaining: 416ms
231:	learn: 4.6933695	total: 126ms	remaining: 416ms
232:	learn: 4.6892345	total: 126ms	remaining: 415ms
233:	learn: 4.6853775	total: 127ms	remaining: 415ms
234:	learn: 4.6812998	total: 127ms	remaining: 414ms
235:	learn: 4.6770741	total: 128ms	remaining: 414ms
236:	learn: 4.6711281	total: 128ms	remaining: 414ms
237:	learn: 4.6698778	total: 129ms	remaining: 413ms
238:	learn: 4.6677370	total: 130ms	remaining: 412ms
239:	learn: 4.6658649	total: 130ms	remaining: 412ms
240:	learn: 4.6631934	total: 131ms	remaining: 411ms
241:	learn: 4.6613074	total: 131ms	remaining: 411ms
242:	learn: 4.6582931	total: 132ms	remaining: 410ms
243:	learn: 4.6579753	total: 132ms	remaining: 410ms
244:	learn: 4.6528148	total: 133ms	remaining: 409ms
245:	learn: 4.6511794	total: 133ms	remaining: 408ms
246:	learn: 4.6478813	total: 134ms	remaining: 408ms
247:	learn: 4.6431786	total: 134ms	remaining: 407ms
248:	learn: 4.6391180	total: 135ms	remaining: 407ms
249:	learn: 4.6381653	total: 135ms	remaining: 406ms
250:	learn: 4.6362860	total: 136ms	remaining: 406ms
251:	learn: 4.6335198	total: 136ms	remaining: 405ms
252:	learn: 4.6290224	total: 137ms	remaining: 405ms
253:	learn: 4.6285421	total: 138ms	remaining: 404ms
254:	learn: 4.6220678	total: 138ms	remaining: 404ms
255:	learn: 4.6168558	total: 139ms	remaining: 403ms
256:	learn: 4.6158399	total: 139ms	remaining: 403ms
257:	learn: 4.6139856	total: 140ms	remaining: 402ms
258:	learn: 4.6098508	total: 140ms	remaining: 401ms
259:	learn: 4.6080409	total: 141ms	remaining: 401ms
260:	learn: 4.6024240	total: 141ms	remaining: 400ms
261:	learn: 4.5997831	total: 142ms	remaining: 400ms
262:	learn: 4.5984752	total: 142ms	remaining: 399ms
263:	learn: 4.5960195	total: 143ms	remaining: 399ms
264:	learn: 4.5941281	total: 144ms	remaining: 398ms
265:	learn: 4.5884916	total: 144ms	remaining: 397ms
266:	learn: 4.5846801	total: 145ms	remaining: 397ms
267:	learn: 4.5784470	total: 145ms	remaining: 396ms
268:	learn: 4.5768444	total: 146ms	remaining: 396ms
269:	learn: 4.5736254	total: 146ms	remaining: 395ms
270:	learn: 4.5674138	total: 147ms	remaining: 395ms
271:	learn: 4.5637863	total: 147ms	remaining: 394ms
272:	learn: 4.5602753	total: 148ms	remaining: 393ms
273:	learn: 4.5559986	total: 148ms	remaining: 393ms
274:	learn: 4.5530395	total: 149ms	remaining: 392ms
275:	learn: 4.5514694	total: 149ms	remaining: 392ms
276:	learn: 4.5497166	total: 150ms	remaining: 391ms
277:	learn: 4.5466853	total: 150ms	remaining: 391ms
278:	learn: 4.5430342	total: 151ms	remaining: 390ms
279:	learn: 4.5385446	total: 151ms	remaining: 389ms
280:	learn: 4.5368070	total: 152ms	remaining: 389ms
281:	learn: 4.5333619	total: 153ms	remaining: 388ms
282:	learn: 4.5286987	total: 153ms	remaining: 388ms
283:	learn: 4.5231717	total: 154ms	remaining: 388ms
284:	learn: 4.5163064	total: 154ms	remaining: 387ms
285:	learn: 4.5106631	total: 155ms	remaining: 387ms
286:	learn: 4.5051658	total: 155ms	remaining: 386ms
287:	learn: 4.5041592	total: 156ms	remaining: 386ms
288:	learn: 4.5004775	total: 157ms	remaining: 386ms
289:	learn: 4.4988287	total: 158ms	remaining: 386ms
290:	learn: 4.4942885	total: 158ms	remaining: 385ms
291:	learn: 4.4892381	total: 159ms	remaining: 385ms
292:	learn: 4.4855132	total: 159ms	remaining: 384ms
293:	learn: 4.4822723	total: 160ms	remaining: 384ms
294:	learn: 4.4743060	total: 160ms	remaining: 383ms
295:	learn: 4.4694710	total: 161ms	remaining: 383ms
296:	learn: 4.4651514	total: 162ms	remaining: 383ms
297:	learn: 4.4634813	total: 162ms	remaining: 382ms
298:	learn: 4.4574913	total: 163ms	remaining: 382ms
299:	learn: 4.4540110	total: 163ms	remaining: 381ms
300:	learn: 4.4506510	total: 164ms	remaining: 381ms
301:	learn: 4.4479347	total: 165ms	remaining: 380ms
302:	learn: 4.4447691	total: 165ms	remaining: 380ms
303:	learn: 4.4386468	total: 166ms	remaining: 379ms
304:	learn: 4.4373872	total: 166ms	remaining: 379ms
305:	learn: 4.4361302	total: 167ms	remaining: 378ms
306:	learn: 4.4328775	total: 167ms	remaining: 378ms
307:	learn: 4.4283748	total: 168ms	remaining: 377ms
308:	learn: 4.4254227	total: 168ms	remaining: 377ms
309:	learn: 4.4238548	total: 169ms	remaining: 376ms
310:	learn: 4.4188242	total: 169ms	remaining: 375ms
311:	learn: 4.4163627	total: 170ms	remaining: 375ms
312:	learn: 4.4120796	total: 171ms	remaining: 374ms
313:	learn: 4.4104495	total: 171ms	remaining: 374ms
314:	learn: 4.4067033	total: 172ms	remaining: 373ms
315:	learn: 4.4040063	total: 172ms	remaining: 373ms
316:	learn: 4.4034117	total: 173ms	remaining: 372ms
317:	learn: 4.4016489	total: 173ms	remaining: 372ms
318:	learn: 4.3991792	total: 174ms	remaining: 372ms
319:	learn: 4.3983962	total: 175ms	remaining: 371ms
320:	learn: 4.3972999	total: 175ms	remaining: 370ms
321:	learn: 4.3904696	total: 176ms	remaining: 370ms
322:	learn: 4.3888032	total: 176ms	remaining: 369ms
323:	learn: 4.3882196	total: 177ms	remaining: 369ms
324:	learn: 4.3854184	total: 177ms	remaining: 368ms
325:	learn: 4.3821073	total: 178ms	remaining: 368ms
326:	learn: 4.3776042	total: 178ms	remaining: 367ms
327:	learn: 4.3762251	total: 179ms	remaining: 367ms
328:	learn: 4.3709337	total: 180ms	remaining: 366ms
329:	learn: 4.3669789	total: 180ms	remaining: 366ms
330:	learn: 4.3652703	total: 181ms	remaining: 365ms
331:	learn: 4.3642613	total: 181ms	remaining: 365ms
332:	learn: 4.3624834	total: 182ms	remaining: 364ms
333:	learn: 4.3587259	total: 182ms	remaining: 363ms
334:	learn: 4.3552908	total: 183ms	remaining: 363ms
335:	learn: 4.3484195	total: 183ms	remaining: 362ms
336:	learn: 4.3446440	total: 184ms	remaining: 362ms
337:	learn: 4.3401554	total: 184ms	remaining: 361ms
338:	learn: 4.3336842	total: 185ms	remaining: 361ms
339:	learn: 4.3291103	total: 186ms	remaining: 360ms
340:	learn: 4.3238492	total: 186ms	remaining: 360ms
341:	learn: 4.3171597	total: 187ms	remaining: 359ms
342:	learn: 4.3145562	total: 187ms	remaining: 359ms
343:	learn: 4.3125090	total: 188ms	remaining: 358ms
344:	learn: 4.3097289	total: 188ms	remaining: 358ms
345:	learn: 4.3069636	total: 189ms	remaining: 357ms
346:	learn: 4.3027095	total: 189ms	remaining: 357ms
347:	learn: 4.2996690	total: 190ms	remaining: 356ms
348:	learn: 4.2957352	total: 191ms	remaining: 355ms
349:	learn: 4.2930425	total: 191ms	remaining: 355ms
350:	learn: 4.2907806	total: 192ms	remaining: 354ms
351:	learn: 4.2873276	total: 192ms	remaining: 354ms
352:	learn: 4.2855192	total: 193ms	remaining: 353ms
353:	learn: 4.2852330	total: 193ms	remaining: 353ms
354:	learn: 4.2846134	total: 194ms	remaining: 352ms
355:	learn: 4.2822217	total: 194ms	remaining: 352ms
356:	learn: 4.2794995	total: 195ms	remaining: 351ms
357:	learn: 4.2768358	total: 195ms	remaining: 350ms
358:	learn: 4.2763974	total: 196ms	remaining: 350ms
359:	learn: 4.2706439	total: 196ms	remaining: 349ms
360:	learn: 4.2695890	total: 197ms	remaining: 349ms
361:	learn: 4.2676379	total: 198ms	remaining: 348ms
362:	learn: 4.2645632	total: 198ms	remaining: 348ms
363:	learn: 4.2642569	total: 199ms	remaining: 347ms
364:	learn: 4.2617171	total: 199ms	remaining: 347ms
365:	learn: 4.2597817	total: 200ms	remaining: 346ms
366:	learn: 4.2585074	total: 200ms	remaining: 345ms
367:	learn: 4.2544801	total: 201ms	remaining: 345ms
368:	learn: 4.2517248	total: 201ms	remaining: 344ms
369:	learn: 4.2473669	total: 202ms	remaining: 344ms
370:	learn: 4.2444907	total: 202ms	remaining: 343ms
371:	learn: 4.2390177	total: 203ms	remaining: 343ms
372:	learn: 4.2360796	total: 204ms	remaining: 342ms
373:	learn: 4.2299985	total: 204ms	remaining: 342ms
374:	learn: 4.2264329	total: 205ms	remaining: 341ms
375:	learn: 4.2222774	total: 205ms	remaining: 341ms
376:	learn: 4.2180792	total: 206ms	remaining: 340ms
377:	learn: 4.2158740	total: 206ms	remaining: 340ms

In [332]:
eval_metrics.sort_values(by='test_r2', ascending=False)

,train_mse,train_mae,train_r2,test_mse,test_mae,test_r2
Ridge,27.683850,4.191183,0.881906,31.696767,4.520806,0.849252
Linear Regression,27.679147,4.190166,0.881926,31.714095,4.525041,0.849170
Catboost,9.188661,2.348648,0.960803,37.116427,4.920299,0.823477
Random Forest,5.062578,1.778006,0.978404,39.190432,5.000033,0.813613
Ada Boost,32.440794,4.614707,0.861614,41.849242,5.151447,0.800968
SVR,46.936731,5.142434,0.799778,43.344110,5.231700,0.793858
Lasso,41.854900,5.108302,0.821456,43.689100,5.213810,0.792218
Xgboost,0.844167,0.585941,0.996399,49.029346,5.550318,0.766820
K Neighbors,32.770850,4.539250,0.860206,51.301800,5.793000,0.756012
Decision Tree,0.185000,0.030000,0.999211,67.900000,6.540000,0.677072